name: 'Set Up Environment'
desciption: 'Get the code, set up java, maven and config git user.'
runs:
  using: 'composite'
  steps:
    # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Get the code
      uses: actions/checkout@v4            
    # Set up Java
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt-hotspot'
        java-version: '8'
        #Cache dependencies to speed up workflow runs.
        cache: maven
        #Value of the distributionManagement/repository/id field of the pom.xml
        server-id: github
    # Configure user for the next step
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions" 
      shell: bash